### ISSUE TITLE
GetPackages extra call to FileExists

### ISSUE THREAD

**Issue by MrAntix** [SymbolSource/SymbolSource.Community#10]
GetPackagePathFromVersion returns a relative path, another dependant GetPackageLink expects relative too
It returns null if the file doesn't exist so, the extra one could be removed

I'd suggest line 164 

```
                    .Where(version => File.Exists(GetPackagePathFromVersion(version))))
```

could be

```
                    .Where(version => GetPackagePathFromVersion(version) != null))
```

or better still a new function which returns true given a version

```
                    .Where(ExistsPackageByVersion)
```

**Comment by TripleEmcoder** [comment]
This project is deprecated in favor of https://github.com/SymbolSource/SymbolSource - closing as won't fix.
