### ISSUE TITLE
NuGet.Core.DownloadController.Search is case sensitive

### ISSUE THREAD

**Issue by MrAntix** [SymbolSource/SymbolSource.Community#11]
Line 198

packagesAdapters = packagesAdapters.Where(p => p.Title.Contains(searchTerm) || p.Version.Contains(searchTerm));

it would make stuff easier to find if it weren't

**Comment by TripleEmcoder** [comment]
This project is deprecated in favor of https://github.com/SymbolSource/SymbolSource - closing as won't fix.
