### ISSUE TITLE
Package submission failed: Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by adam-resdiary** [SymbolSource/SymbolSource.Community#23]
I've setup the SymbolSource server by following the guide at http://www.xavierdecoster.com/setting-up-your-own-symbolsource-server-step-by-step.

When I try to run a nuget push, I get the following error message:

> Failed to process request. 'Package submission failed: Arithmetic operation resulted in an overflow.. See http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing this error if your client discards attached detailed information.'. The remote server returned an error: (506) Package submission failed: Arithmetic operation resulted in an overflow.. See http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing this error if your client discards attached detailed information...

Any idea how I can diagnose what the problem is or fix this?

**Comment by TripleEmcoder** [comment]
This project is deprecated in favor of https://github.com/SymbolSource/SymbolSource - closing as won't fix.
