### ISSUE TITLE
The controller for path '/NuGet' could not be found or it does not implement IController

### ISSUE THREAD

**Issue by mikeborozdin** [SymbolSource/SymbolSource.Community#31]
Hi,

I followed the instructions [here](http://www.xavierdecoster.com/setting-up-your-own-symbolsource-server-step-by-step). And I managed to run the server using Visual Studio and IIS Express. The self-diagnostics says everything is fine. However, `App_Data` is full of errors saying: 

`The controller for path '/NuGet' could not be found or it does not implement IController`.

It happens either when I'm using `nuget push` or run the diagnostics. Interestingly, in both cases, I receive a successful message. However, nothing happens - and no package gets deployed.

**Comment by twenzel** [comment]
I also get this error. Any advices?

**Comment by petunes** [comment]
I am also experiencing this issue after following the same tutorial.

**Comment by MichaelCommo** [comment]
I also get this error logged with each push request made.  Does not seem to inhibit any of the functionality of the symbolsource server, but it does crowd the logs folder unnecessarily.

**Comment by npbenjohnson** [comment]
Got it, vs sets up a default route in mvc projects that interferes with attribute routing, so just delete this from RouteConfig.cs
```
            routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
            );
```

**Comment by dotMorten** [comment]
Same issue here. However when I do nuget push, I get a 404 back and the package didn't uploaded. The package push test does however pass.

The suggested workaround to remove the MapRoute doesn't fix the 404 error either (just the error logging). I'm still not able to push a source package to the server (and no error is logged when I do)

**Comment by TripleEmcoder** [comment]
This project is deprecated in favor of https://github.com/SymbolSource/SymbolSource - closing as won't fix.
