### ISSUE TITLE
Is this project maintained at all?

### ISSUE THREAD

**Issue by michael-x** [SymbolSource/SymbolSource.Community#33]
I've raised issue #32 a while ago and two other users have reported having the same issue, but I have not seen an official response from a maintainer in any of the recent issues.
As a company we are not allowed to upload our source code to the internet. Therefore we need an on-sight solution for publishing symbol packages. We've established a working build process including a SymbolSource.Community symbol package server, but now cannot switch to using VS 2015, because the symbol package server doesn't support it.
I need to know whether any advice/help/update can be expected on issues reported here, or whether we need to look for a different (free or commercial) symbol server implementation.
[I know that the project is called SymbolSource._Community_, but as issue #32 has been fixed for the official SymbolSource server it would probably take someone who knows what he is doing an hour or so to also fix the problem for the Community edition while trying to do that as an outsider it's not even sure, if all the resources required to fix the issue are even publicly available.]

**Comment by TripleEmcoder** [comment]
This project is deprecated in favor of https://github.com/SymbolSource/SymbolSource - closing as won't fix.
