### ISSUE TITLE
1.3.3 AND nuget 2.8 and  Windows 10 kit

### ISSUE THREAD

**Issue by kargenc** [SymbolSource/SymbolSource.Community#34]
İs this project Die.  NOT working with nuget 2.8 and Windows 10 SDK getting error custom metadata İtem 6 and ı cant Fix İt and NO Solution on  google

Any advice

**Comment by mwijnands** [comment]
I posted a fix that I think will also resolve your issue here: #32

**Comment by TripleEmcoder** [comment]
This project is deprecated in favor of https://github.com/SymbolSource/SymbolSource - closing as won't fix.
