### ISSUE TITLE
Visual Studio 2015 Incompatibility

### ISSUE THREAD

**Issue by adamtoakley** [SymbolSource/SymbolSource.Community#37]
Pushing Packages Created From Visual Studio 2015 .csproj files (I.E. `# nuget pack MyProject.csproj -Symbols`) fails.

The error is:

> Package submission failed: Unknown custom metadata item kind: 7

There is another nuget package that is out there that fixes this issue. it's found at: [https://www.nuget.org/packages/CustomMetadataFix.Microsoft.Cci.Metadata/](https://www.nuget.org/packages/CustomMetadataFix.Microsoft.Cci.Metadata/)

Is it possible to include this fix with this package?

**Comment by andiges** [comment]
duplicate of [#32](https://github.com/SymbolSource/SymbolSource.Community/issues/32)

**Comment by TripleEmcoder** [comment]
This project is deprecated in favor of https://github.com/SymbolSource/SymbolSource - closing as won't fix.
