### ISSUE TITLE
Symbol source fail on iis 7.5

### ISSUE THREAD

**Issue by georgiuk** [SymbolSource/SymbolSource.Community#7]
Hello,
I am trying to set up y own symbol source server. When I try it in debug mode in visual studio it seems to work fine, however when i deploy it in IIS 7.5 (win server 2008 x64) it fails with error :

No component for supporting the service MvcApplication1.Controllers.HomeController was found

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Castle.MicroKernel.ComponentNotFoundException: No component for supporting the service MvcApplication1.Controllers.HomeController was found

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[ComponentNotFoundException: No component for supporting the service MvcApplication1.Controllers.HomeController was found]
   Castle.MicroKernel.DefaultKernel.Resolve(Type service) in c:\TeamCity\buildAgent\work\83ad55e3df18b1a8\src\Castle.Windsor\MicroKernel\DefaultKernel_Resolve.cs:152
   SymbolSource.Server.Basic.MCControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType) +366
   System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName) +93
   System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory) +305
   System.Web.Mvc.<>c__DisplayClass6.<BeginProcessRequest>b__2() +71
   System.Web.Mvc.<>c__DisplayClassb`1.<ProcessInApplicationTrust>b__a() +19
   System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust(Func`1 func) +161
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +389
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +371

Do you have any idea why is this happening. I am very noob  in MVC3.
Thank you 
Kostas

**Comment by TripleEmcoder** [comment]
This project is deprecated in favor of https://github.com/SymbolSource/SymbolSource - closing as won't fix.
